apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: techtrends-staging
  namespace: staging
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values-staging.yaml
    path: solutions/helm/nginx-deployment
    repoURL: https://github.com/rickeand/nd064_course_1
    targetRevision: HEAD