namespace:
  name: prod

service:
  port: 7111
  targetPort: 3111
  protocol: TCP
  type: ClusterIP

image:
  repository: rickeand/techtrends
  tag: latest
  pullPolicy: Always

replicaCount: 5

resources:
  requests:
    memory: 128Mi
    cpu: 350m
  limits:
    memory: 256Mi
    cpi:  500m

containerPort: 3111
livenessProbe: /healthz
readinessProbe: /healthz