namespace:
  name: staging

service:
  port: 5111
  targetPort: 3111
  protocol: TCP
  type: ClusterIP

image:
  repository: rickeand/techtrends
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 3

resources:
  requests:
    memory: 90Mi
    cpu: 250m #300m
  limits:
    memory: 90Mi #128Mi
    cpi:  250m #500m

containerPort: 3111
livenessProbe: /healthz
readinessProbe: /healthz